### ISSUE TITLE
How to Enable Bluetooth device/controller in Cubienoard (A80)?

### ISSUE THREAD

**Issue by ARUNAKUMARBHAT** [Oline/cubieboard#5]
I am vary beginner to cubieboard4 (A80) as well as Linux. As per the cubieboard4 specification it is having bcm40183b2 (bluetooth 4.0 and WiFi) chip and it is connected through Uart2. 
I can see this in /lib/firmware/ap6330/. And it is having dabian linux 3.4.39.

If I do lsmod I am able to see bnep,hidp,hci_uart,rfcomm, bluetooth modules.

But If I do 
$hcitool dev
Devices:

I am not able to see any controller. Please any one guide me how to enable bluetooth controller for cubieboard4 (A80).

And if i do
$rfkill list it is showing 
0: rtl8723bs: Bluetooth
        Soft blocked: no
        Hard blocked: no

Now again I am confused here. Because rtl8723bs is realtek wifi and BT chip set. But cubieboard4 (A80) spec is telling it is having bcm40183b2 chipset.

Please tell me cubieboard4 is having which chipset?
and how to enable bluetooth controller for cubieboard4 (A80)?

**Comment by Oline** [comment]
Hi, this project doesn't support cubieboard 4 at the moment (mainly because I don't have a cubieboard 4) and it seems that Bluetooth support on the cubieboard 4 doesn't exist yet in the Linux kernel. I think you will have to wait until someone make it available.

**Comment by Oline** [comment]
You can follow the bluetooth support here : http://linux-sunxi.org/Linux_mainlining_effort
